---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: https://webhook.site/5a6a9644-2631-4466-a527-17928edf7762
sections:
- type: directory
  path: content/recipes
  label: recipe
  create: all
  match: "**/*"
  templates:
  - recipe
- type: directory
  path: content/blog
  label: blog
  create: all
  match: "**/*"
  templates:
  - blog
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
